#!/bin/bash

# peronal build script for compiling newest version of @PAC-ROM and
# uploading it to Dropbox for installation
# Copyright (C) 2015 Andrew King @the-octagon
# https://github.com/the-octagon/projects/
#
# DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
#                    Version 2, December 2004 
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net> 
#
# Everyone is permitted to copy and distribute verbatim or modified 
# copies of this license document, and changing it is allowed as long 
# as the name is changed. 
#
#              DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 
#
# 0. You just DO WHAT THE FUCK YOU WANT TO.
#
#
# Credit/Acknowledgement
# All the Things ASCII Art v0.0.1
# by @briantford 
# https://github.com/btford/allthethings
# Licensed under WTFPL http://sam.zoy.org/wtfpl/
#
#

pur=$(tput setaf 5)    # Purple
ylw=$(tput setaf 3)    # Yellow
txtrst=$(tput sgr0)       # Text reset

while getopts d: option
do
        case "${option}"
        in
                d) DEVICEID=${OPTARG};;
        esac
done

#bash script to private build PAC-ROM ;
toilet --gay -t "moving to Dropbox" ;
cd ~/Dropbox ;
toilet --gay -t "removing old build" ;
rm pac_$DEVICEID*.zip ;
toilet --gay -t "moving to build directory" ;
cd /media/andy/2TBSATAHDD/android/pac-6.0; 
echo " _   _ ___ ___   _ _____ ___     _   _    _      _____ _  _ ___ "
echo "| | | | _ \   \ /_\_   _| __|   /_\ | |  | |    |_   _| || | __|"
echo "| |_| |  _/ |) / _ \| | | _|   / _ \| |__| |__    | | | __ | _| "
echo " \___/|_| |___/_/ \_\_| |___| /_/ \_\____|____|   |_| |_||_|___|"
echo "                             =================="                                 
echo " _____ _  _ ___ _  _  ___ ___ "
echo "|_   _| || |_ _| \| |/ __/ __|"
echo "  | | | __ || ||    | (_ \__ \\"
echo "  |_| |_||_|___|_|\_|\___|___/"


echo "                  ${ylw}~=                                                 ${txtrst}M?${ylw}              ,=~${txtrst}"
echo "                   ${ylw}==                                                ${txtrst}MD${ylw}           ~=~=~${txtrst}"
echo "                   ${ylw}====                                               ${txtrst}+${ylw}        :=~===${txtrst}"
echo "                   ${ylw}~====~                        ~                    ${txtrst}M${ylw}     :~======${txtrst}"
echo "                    ${ylw}~=====~           ~         ==               ~==  ${txtrst}M${ylw}   ~========${txtrst}"
echo "                     ${ylw}~====~~~        ,==       ~==            ,====   ${txtrst}Z${ylw}~~=========${txtrst}"
echo "                     ${ylw}=======~=~      ~===,     ===~          =====   ${txtrst}=${ylw}==========~${txtrst}"
echo "                     ${ylw},===========:   ~=====   :===~       ,======:===${txtrst}~${ylw}~=======~~${txtrst}"
echo "                      ${ylw}=~===========  ~======  ~====     ,~===========${txtrst}+${ylw}========~${txtrst}"
echo "                      ${ylw},~=============~=======~===~=~  ~==============${txtrst}M${ylw}=======~${txtrst}"
echo "                       ${ylw}=============~~======${txtrst}?MNDDM${ylw}~~==========~======${txtrst}M${ylw}~=====~${txtrst}"
echo "                        ${ylw}================${txtrst}M=,,,,,,,,,D${ylw}~======${txtrst}M   N${ylw}=====${txtrst}N${ylw}=====~${txtrst}"
echo "         ${ylw}==~            =================~${txtrst}N~,,,,,,,:M8MMMNM   O M====${txtrst}~${ylw}=====${txtrst}"
echo "          ${ylw},===~,         ~=================~~${txtrst}MM~          M     M====${txtrst}=${ylw}==== ${txtrst}"
echo "            ${ylw}~===~=       :=================~${txtrst}N             OM   M ===${txtrst}?${ylw}~=== ${txtrst}"
echo "              ${ylw}~====~~     ==============${txtrst}M   M     ?M ~   8Z      ~:=${txtrst}N${ylw}~==:${txtrst}"
echo "    M          ${ylw}~======~=~  ============${txtrst}M O     ?M +7MMMMMMMI      8=${txtrst}M${ylw}~==${txtrst}"
echo "   NO:7:        ${ylw}:======================${txtrst}7    M=  MNMMMMMMMMMM       +${txtrst}N${ylw}==${txtrst}"
echo "MMO:::::?         ${ylw}=======================${txtrst}8M~M ~MMMMMMMMMMMMMM      M+${ylw}~~                     ,===~${txtrst}"
echo "M,::::::::N        ${ylw}=======================${txtrst}N  MMMMMMMMMMMMMMMM      M~${ylw}=    :=~~=~         ~=~~==~${txtrst}"
echo ":,:::::::::Z         ${ylw}=====================${txtrst}7    MMMMMMMMMMMMMM      M${ylw}===~=====~       ,=~~====${txtrst}"
echo "?:::::::::::M    ${ylw}==========================${txtrst}M    ~MMMMMMMMMMMM     II${ylw}========      :~=======${txtrst}"
echo " ,::::::::::,     ${ylw},========================~${txtrst}8     MMMMMMMMMMI     M${pur}?M${ylw}======    =======~==${txtrst}"
echo " 8:::::::::::N      ${ylw}===~====================+${txtrst}N    MMMMMMMMMM      I${pur}?I${ylw}===~= ~==========~${txtrst}"
echo "   D:::::::::         ${ylw}======================${txtrst}MM    MMMMMMMMM ,    I${pur}???M${ylw}==~===========${txtrst}"
echo "    N~==OMMZZ7         ${ylw}:================~+${txtrst}M${ylw}===${txtrst}M    8::~,  =N    M${pur}????D${ylw}============~${txtrst}"
echo "           OZZM     ${ylw}~===============~==${txtrst}M${ylw}~~=====${txtrst}M               O${pur}??????${ylw}===========${txtrst}"
echo "           ,MZZM=${ylw}~==================${txtrst}OO${ylw}=~========${txtrst}M~           DD${pur}???????M${ylw}========~${txtrst}"
echo "            ~MZZZ?${ylw}===============${txtrst}MM${ylw}=~===========~${txtrst}7?NMMZZNNM7${pur}?I????????7${ylw}~======${txtrst}"
echo "    ${ylw}~~~~,     ${txtrst}:ZZZM${ylw}============${txtrst}N+${ylw}================${pur}N?????????????????????O${ylw}====~=~~~~~~===~~:,${txtrst}"
echo "     ${ylw}=========~,${txtrst}MOZM${ylw}~=======${txtrst}NN${ylw}====================${pur}M????????????????????N${ylw}==========================,${txtrst}"
echo "      ${ylw}===========${txtrst}MZZO${ylw}=~===${txtrst}M${ylw}~=~====================~${pur}?????????????????????~${ylw}========================~=~${txtrst}"
echo "       ${ylw}~~=========${txtrst}?ZZZNN8${ylw}==========================${pur}MI???????????????????M${ylw}=====================~~${txtrst}"
echo "       ${ylw}=============${txtrst}NMZM${ylw}============================${pur}????????????????????O${ylw}=================~${txtrst}"
echo "        ${ylw}===========~~${txtrst}MZZO${ylw}~==========================${pur}M????????????????????${ylw}============~,${txtrst}"
echo "         ${ylw}=============${txtrst}OZZZN${ylw}=========================${pur}M????????????????????${ylw}~========,${txtrst}"
echo "          ${ylw}~============~${txtrst}MZZM${ylw}~~======================${pur}8????????????????????${ylw}~=====${txtrst}"
echo "           ${ylw}~============~${txtrst}MZZM${ylw}======================~${pur}?????????????????????${ylw}~~===${txtrst}"
rm -v ./.repo/local_manifests/room* ;
repo sync -j32 ;
#because who wants a slow sync ;
toilet --gay -t "cleaning out directory and building PAC" ;
make clean ;
if [ $DEVICEID=="shamu" ]
then
echo "                              8b."
echo "                              888b"
echo "                              8888b"
echo "                              88888b"
echo "                              888888b"
echo "                            .d88888888b.__"
echo "                      _.od888888888888888888boo..._"
echo "                  .od8888888888888888888888888888888booo.._"
echo "               .od888888888888888888888888888888888888888888)"
echo "             .d888P'    \"Y88888888888888888888(_   _ )888P\"'"
echo "           .d8888Poo.     \`Y88888888888888888P-.\`-\`@'.-'\"\"-."
echo "  .oooooood8888888P\"\"'      \`\"Y8888888P.d888P   \`---'\"\"\"\".-'"
echo "d888888888'888P'  _...-----..__      'd88888__...------'"
echo "\`\"\"Y88888'8888|-'              \`----'|88888P"
echo "        \`Y8888b                       Y888P"
echo "         888888b                       \`\"'"
echo "          Y88888"
echo "           \`Y88P"
echo "             YP"
toilet --gay -t "PLAYER 1 SHAMU START"
fi ;
./build-pac.sh -j4 $DEVICEID ; 
toilet --gay -t "copying new build to Dropbox" ;
cp ./out/target/product/$DEVICEID/*.zip ~/Dropbox ;

